language: r
sudo: false
warnings_are_errors: true

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - decompr
  - diagonals
  - rmarkdown

after_success:
  - Rscript -e 'library(covr);coveralls()'
